// Typed-request routing: what a first-time visitor might type, and what the demo must do with it.
// 'refuse' = a negated request (or one for the chip's opposite) is not turned around; 'clarify' = the chips come back,
// with the closest named when there is one; anything else = the start of the chip it must run. An optional third
// element pins `via` ('none' = no via; 'question', 'check' and 'statement' for text that asks or tells rather than
// requests). Uses interpret(), the same function main.js calls.
import { interpret, asksWhatIfFails } from '../js/engine/match.js';

// A visitor pasting a long story: 2000 characters with no clear request.
const LONG = ('So, a bit of background first: my partner and I travel a lot for work, and the flat sits empty for days at a time. ' +
  'We have a cat sitter who pops in twice a week, but she can never remember which plant needs what, and last time half of them wilted. ').repeat(6).slice(0, 2000);

export const CASES = {
  home: [
    // already in the tests
    ["I'm away until Sunday, keep the place looking lived in", "I'm away"],
    ['dont let my plants die', "I'm away"],
    ['water my plants while im away', 'Just keep the plants alive'],
    ["don't forget to water the plants", 'Just keep the plants alive'],
    ['make it look like someones home at night', 'Make it look like someone'],
    ['let me know if someone rings the doorbell', 'Hold the house'],
    ['keep an eye on the front door', 'Hold the house'],
    ["keep the house warm while I'm away", 'Hold the house'],
    ["don't let the pipes freeze while I'm gone", 'Hold the house'],
    ["what's the weather like", 'clarify'],
    // from the wf4 review suggestions
    ["water my plants while I'm on holiday", 'Just keep the plants alive'],
    ["water the plants while I'm on vacation", 'Just keep the plants alive'],
    ["I'm travelling for a week, water the plants", 'Just keep the plants alive'],
    ["I'm away for a week, water the plants", 'Just keep the plants alive'],
    ["I'm on holiday", "I'm away"],
    ["I'm away for a week", "I'm away"],
    ['arm the camera', 'Hold the house'],
    ['just arm the camera', 'Hold the house'],
    ['turn off the heating', 'clarify'],
    ['keep the heating off', 'clarify'],
    ['stop watering', 'clarify'],
    ['turn the lights off', 'clarify'],
    ['set it to 25 degrees', 'clarify'],
    ['heat the house to 22', 'clarify'],
    ['no heating please', 'refuse'],
    ['set the heating to 25 degrees', 'clarify'],
    ['turn the heating off', 'clarify'],
    ['stop watering the plants', 'clarify'],
    ['no watering', 'refuse'],
    ["can you water the plants while I'm on holiday", 'Just keep the plants alive'],
    ["I'm off to Spain for a week, keep the place looking lived in", "I'm away"],
    ["hold the house at 19 degrees, don't record anything", 'Hold the house'],
    ['keep the plants alive but leave the blinds open', 'clarify'],
    ['only the plants please', 'Just keep the plants alive'],
    ["keep the camera on while I'm away", 'clarify'],
    ['away for a week, keep the blinds open', 'clarify'],
    // wf5: more phrasings, typos, casing, emoji, rambling, questions, negations, opposites, other numbers, units and devices, several requests at once, edge input
    ['water the plants and hold the house at 19', 'clarify'],
    ["make it look like someone's home and water the plants", 'clarify'],
    ['just the heating', 'clarify'],
    ['only the door camera', 'Hold the house'],
    ['can you not water the plants', 'refuse'],
    ['Im away next week, look after the place', "I'm away"],
    ['going on holiday for 2 weeks, make it look lived in', 'clarify'],
    ['WATER THE PLANTS', 'Just keep the plants alive'],
    ['water the plants 🌱🌱', 'Just keep the plants alive'],
    ['watr the plnts', 'clarify'],
    ['keep the plants watered', 'Just keep the plants alive'],
    ['just the plants', 'Just keep the plants alive'],
    ['make it look like someone is home', 'Make it look like someone'],
    ["what's the temperature", 'clarify'],
    ['set the thermostat to 19', 'Hold the house'],
    ['keep it at 19 degrees', 'Hold the house'],
    ['keep it at 21 degrees', 'clarify'],
    ['hold the house at 19°F', 'clarify'],
    ['tell me if someone comes to the door', 'Hold the house'],
    ["who's at the door?", 'clarify'],
    ["don't water the plants", 'refuse', 'none'],
    ['let the plants die', 'refuse', 'opposite'],
    ['let the pipes freeze', 'refuse', 'opposite'],
    ["I'm not going away", 'refuse'],
    ['turn off the lamp', 'clarify'],
    ['close the blinds', 'clarify'],
    ["keep the blinds closed while I'm away", 'clarify'],
    ["make the place look lived in but don't turn on any lights", 'clarify'],
    ["make it look like someone's home but leave the lights off", 'clarify'],
    ['im away for a week make the place look lived in and dont let my plants die', "I'm away"],
    ['hold the house at 19 and let me know if anyone comes by', 'Hold the house'],
    ['what about the plants?', 'clarify'],
    ['', 'clarify'],
    ['   ', 'clarify'],
    ['?!?!...', 'clarify'],
    ['12345', 'clarify'],
    ['arrosez les plantes', 'clarify'],
    ['请帮我浇花', 'clarify'],
    ['https://example.com/water-the-plants', 'clarify'],
    // wf6 engine round: the opposite of lived-in, questions, pictures, the plan's own thresholds (in their role), rules vs
    // plain switch-ons, a request to be told, and cross-scene rule stops
    ["make it look like nobody's home", 'refuse', 'opposite'],
    ['make it look like no one is home', 'refuse', 'opposite'],
    ['is anyone at the door', 'clarify', 'question'],
    ['is someone at the door?', 'clarify', 'question'],
    ['hold the house at 19 and tell me if anyone comes to the door, no pictures', 'clarify', 'conflict'],
    ['tell me if anyone comes to the door, no photos', 'clarify', 'conflict'],
    ['hold the house at 19°C and message me if it drifts more than 2 degrees', 'Hold the house'],
    ['hold the house at 19°C and message me if it drifts more than 2°', 'Hold the house'],
    ['water the plants when the soil is below 30 percent', 'Just keep the'],
    ['hold the house at 2 degrees', 'clarify', 'values'],
    ['keep the house at 2°C', 'clarify', 'values'],
    ['set the heating to 2', 'clarify', 'values'],
    ['water the plants at 30%', 'clarify', 'values'],
    ['water the plants above 30%', 'clarify', 'values'],
    ["I'm away for a week, keep the heating at 21", 'clarify', 'values'],
    ['water the plants when the soil is below 20 percent', 'clarify', 'values'],
    ['water the plants when the soil drops under 20%', 'clarify', 'values'],
    ['keep the plants alive, water them only below 20%', 'clarify', 'values'],
    ['message me if the soil is below 30%', 'clarify', 'values'],
    ['just keep the plants alive and text me if the soil goes under 30 percent', 'clarify', 'values'],
    ['keep the plants alive and message me if the sensor reads below 20%', 'Just keep the'],
    ['water the plants for 40 seconds when the soil is below 30%', 'Just keep the'],
    ['water the plants and turn on the lamp', 'clarify', 'partial'],
    ['keep the lamp on in the evenings and water the plants', 'clarify', 'partial'],
    ['water the plants and keep the blinds closed', 'clarify', 'conflict'],
    ['hold the house at 19 and turn on the lamp', 'clarify', 'partial'],
    ['hold the house at 19 and close the blinds', 'clarify', 'partial'],
    ['hold the house at 19 and lock the door', 'clarify', 'partial'],
    ['lock the door', 'clarify', 'partial'],
    ["I'm away for a week, feed the cat", 'clarify', 'partial'],
    ['make it look like someone is home in the mornings', 'clarify', 'partial'],
    ["make it look like someone's home in the afternoon", 'clarify', 'partial'],
    ["water the plants but don't turn on the lamp", 'Just keep the'],
    ['water the plants lightly', 'Just keep the'],
    ['start the thermostat', 'Hold the house'],
    ['run the thermostat', 'Hold the house'],
    ["do you think you could make it look like someone's home in the evenings?", 'Make it look'],
    ["once I've left, turn the heating off", 'clarify', 'partial'],
    ['when I leave, turn the lights off', 'clarify', 'partial'],
    ['tell me if the camera is not armed', 'clarify', 'conflict'],
    ["make sure my plants don't die while I'm away", "I'm away for"],
    ["I don't want my plants to die", "I'm away for"],
    ['my plants must not die', "I'm away for"],
    // close as nearness or care, "leave X alone", and keeping off what the chip rules out
    ['keep a close eye on the front door', 'Hold the house'],
    ['watch the door closely', 'Hold the house'],
    ['tell me if anyone gets close to the door', 'Hold the house'],
    ['water the plants and leave the heating alone', 'Just keep the plants alive'],
    ['keep the plants alive, and keep the lights off', 'Just keep the plants alive'], // the lamp starts off and stays off
    ['hold the house at 19 and give me feedback', 'Hold the house'], // "feedback" is no "feed"
    // polish round: the heating stays on at its own setting (touches), so keeping it off asks back; the plant plan
    // keeps the blinds open outside 13:00–17:00, so closing them at night asks back
    ['make it look like someone is home and keep the heating off', 'clarify', 'conflict'],
    ["Make it look like someone's home in the evenings and keep the heating off", 'clarify', 'conflict'],
    ['Just keep the plants alive and keep the heating off', 'clarify', 'conflict'],
    ["Water the plants while I'm away and leave the heating off", 'clarify', 'conflict'],
    ['keep the plants alive and keep the thermostat off', 'clarify', 'conflict'],
    ['water the plants, no heating', 'Just keep the plants alive'], // leaves the heating out, as the plan does
    ['Water the plants and close the blinds at night', 'clarify', 'partial'],
    ['Keep the plants alive and shut the blinds at night', 'clarify', 'partial'],
    ['water the plants and close the blinds at dusk', 'clarify', 'partial'],
    ['water the plants and close the blinds when it gets dark', 'clarify', 'partial'],
    ['water my plants and close the blinds every evening', 'clarify'], // a tie with the evening presence plan
    ['water the plants every night', 'clarify', 'partial'],
    ['water the plants and close the blinds in the afternoon', 'Just keep the plants alive'], // 13:00–17:00, as planned
    ['water the plants tonight', 'Just keep the plants alive'],
    ["I'm away for a week, close the blinds at night", "I'm away"], // its blinds close as the sun sets
    // final round: the plant plan's night words are phrases with the blinds (or "every night"), so a stay over the
    // holidays, for a few nights or until Sunday night, a dark corner or warm evenings still run it; "over" is no
    // "overnight" and "after" no "afternoons" (a close form needs an ending, not another word)
    ['water the plants and close the blinds overnight', 'clarify', 'partial'],
    ['water my plants over the holidays', 'Just keep the plants alive'],
    ['keep my plants alive over the next few days', 'Just keep the plants alive'],
    ["I'm away over Easter, water the plants", 'Just keep the plants alive'],
    ['keep my plants alive over the weekend', 'Just keep the plants alive'],
    ["keep my plants alive while I'm over in Paris", 'Just keep the plants alive'],
    ["I'm away for a few nights, water my plants", 'Just keep the plants alive'],
    ['keep my plants alive for a few nights', 'Just keep the plants alive'],
    ["I'm gone for two nights, keep the plants alive", 'Just keep the plants alive'],
    ["I'm away overnight, water the plants", 'Just keep the plants alive'],
    ['keep the plants alive until Sunday night', 'Just keep the plants alive'],
    ["keep my plants alive while I'm away, I'll be back late at night", 'Just keep the plants alive'],
    ['water my plants, they sit in a dark corner', 'Just keep the plants alive'],
    ["Water my plants while I'm away, they're in a dark room", 'Just keep the plants alive'],
    ['keep the plants alive, it gets dark early here', 'Just keep the plants alive'],
    ['keep the plants alive, the evenings are warm', 'Just keep the plants alive'],
    ["water the plants while I'm on my night shifts", 'Just keep the plants alive'],
    ["make it look like someone's home after dark", 'Make it look like someone'],
    // "…but leave the camera off" to a plan that arms it
    ["make it look like someone's home but leave the camera off", 'clarify', 'conflict'],
    ["I'm away for a week but leave the camera off", 'clarify', 'conflict'],
    ['hold the house at 19 but keep the camera off', 'clarify', 'conflict'],
    [LONG, 'clarify'],
  ],
  lab: [
    // already in the tests
    ['open the shutter please', 'Open the shutter'],
    ['open the shutter then close it after a second', 'Open the shutter'],
    ['rotate the mirror slightly and read the meter', 'Tilt M2'],
    ['move stage x to 12.4mm', 'Move stage X'],
    ['align the beam', 'Walk M2'],
    ['max power', 'Walk M2'],
    ['do not open the shutter', 'refuse', 'none'],
    ['close the shutter', 'refuse', 'opposite'],
    ['turn off the laser', 'refuse', 'opposite'],
    ['keep the shutter closed, do not open it', 'refuse'],
    ["don't touch anything", 'refuse'],
    ["what's the power reading", 'clarify'],
    ['r u a real lab?', 'clarify'],
    // from the wf4 review suggestions
    ['tilt M1 by 0.05 in pitch', 'clarify'],
    ['tilt M2 by 0.2 degrees', 'clarify'],
    ['move stage X to 15 mm', 'clarify'],
    ['open the shutter at 50 mW', 'clarify'],
    ['open the shutter at 5 mW', 'Open the shutter'],
    ['measure the power', 'clarify'],
    ['stop', 'clarify'],
    ['stop the laser', 'clarify'],
    ['kill the laser', 'clarify'],
    ["you shouldn't open the shutter", 'refuse'],
    ['nudge mirror 2 a bit in yaw and tell me the power', 'Tilt M2'],
    ["don't open the shutter, just move stage X to 12.4 mm", 'clarify'],
    ['move stage X to 12.4 mm without opening the shutter', 'clarify'],
    ['walk M2 but leave the shutter closed', 'clarify'],
    ['move stage X to 12.4 mm with the shutter closed', 'clarify'],
    ["tilt M2 +0.05 yaw but don't touch the stage", 'Tilt M2'],
    // wf5: more phrasings, typos, casing, emoji, rambling, questions, negations, opposites, other numbers, units and devices, several requests at once, edge input
    ['open the shutter and move stage X to 12.4 mm', 'Move stage X'],
    ['open the shutter and align the beam', 'clarify'],
    ['move stage X to 12.4 mm and report the power', 'Move stage X'],
    ['tilt M2 and walk it to maximise power', 'clarify'],
    ['could you not close the shutter', 'refuse', 'none'],
    ['ok, what is the power?', 'clarify'],
    ['OPEN THE SHUTTER', 'Open the shutter'],
    ['open shutter 5mW', 'Open the shutter'],
    ['open the shutter at 5 W', 'clarify'],
    ['open the shutter at 0.5 mW', 'clarify'],
    ['shut the shutter', 'refuse', 'opposite'],
    ['close shutter pls', 'refuse'],
    ['block the beam', 'refuse', 'opposite'],
    ["don't close the shutter", 'refuse', 'none'],
    ['turn on the laser', 'Open the shutter'],
    ['tilt M2 by 0.05 degrees in yaw', 'Tilt M2'],
    ['tilt m2 by -0.05 yaw', 'clarify'],
    ['tilt M2 +0.05° yaw and report the power', 'Tilt M2'],
    ['tilt mirror 2 in pitch', 'clarify'],
    ['report the power meter', 'clarify'],
    ['move stage X to 12.4 mm', 'Move stage X'],
    ['move stage X to 12.4 cm', 'clarify'],
    ['move stage Y to 12.4 mm', 'clarify'],
    ['move the stage to 12.4mm in 0.1mm steps', 'Move stage X'],
    ['move the stage to 12.4mm in 1 mm steps', 'clarify'],
    ["move stage X to 12.4 mm but don't log anything", 'clarify'],
    ['maximise the power', 'Walk M2'],
    ['optimise alignment', 'Walk M2'],
    ['walk M1 to maximise power', 'clarify'],
    ['walk m2, stop if it drops more than 10%', 'clarify'],
    ['what is the laser power?', 'clarify'],
    ['how much power is on the meter?', 'clarify'],
    ["tilt M2 by +0.050 in yaw but don't open the shutter", 'clarify'],
    ['close the shutter and move stage X to 12.4 mm', 'clarify'],
    ['open the shutter for 10 seconds then close it', 'clarify'],
    ["don't touch M1", 'refuse'],
    ['emergency stop', 'clarify'],
    ['Tilt M2 by +0.050° in yaw, then report the power meter', 'Tilt M2'],
    ['', 'clarify'],
    ['...', 'clarify'],
    ['0.05', 'clarify'],
    ['öffne den Verschluss', 'clarify'],
    ['www.thorlabs.com/shutter', 'clarify'],
    // wf6 engine round: questions, checks and statements are not requests (polite requests still are); leave X alone;
    // negated names; the plan's own stop rule and thresholds
    ['is it safe to open the shutter?', 'clarify', 'question'],
    ['is the shutter open?', 'clarify', 'question'],
    ['the shutter is open', 'clarify', 'statement'],
    ['I already opened the shutter', 'clarify', 'statement'],
    ['tell me if the shutter is open', 'clarify', 'check'],
    ['let me know if the shutter is open', 'clarify', 'check'],
    ['tell me whether the laser is on', 'clarify', 'check'],
    ['check the shutter', 'clarify', 'check'],
    ['check if the shutter is open', 'clarify', 'check'],
    ['check whether the shutter is open', 'clarify', 'check'],
    ['can you check if the shutter is open?', 'clarify', 'check'],
    ['verify the shutter is open', 'clarify', 'check'],
    ['confirm the beam is on the meter', 'clarify', 'check'],
    ['can I open the shutter?', 'clarify', 'question'],
    ['may I open the shutter?', 'clarify', 'question'],
    ['am I allowed to open the shutter?', 'clarify', 'question'],
    ['shutter open?', 'clarify', 'question'],
    ['laser on?', 'clarify', 'question'],
    ['laser is on', 'clarify', 'statement'],
    ["shutter's open", 'clarify', 'statement'],
    ['should I open the shutter?', 'clarify', 'question'],
    ['can you open the shutter', 'Open the shutter'],
    ['could you open the shutter?', 'Open the shutter'],
    ['will you open the shutter', 'Open the shutter'],
    ['is it possible to open the shutter at 5.0 mW and hold?', 'Open the shutter'],
    ['are you able to walk M2 to maximise power on the meter?', 'Walk M2 to'],
    ['do you think you could move stage X to 12.400 mm in 0.100 mm steps?', 'Move stage X'],
    ['how about you tilt M2 by +0.050° in yaw, then report the power meter', 'Tilt M2 by'],
    ['maximise the power but leave M2 alone', 'clarify', 'conflict'],
    ['walk M2 but leave the stage alone', 'Walk M2 to'],
    ['walk M2 and stop on a 20% drop', 'Walk M2 to'],
    ["walk M2 but don't touch M1", 'Walk M2 to'],
    ["tilt M2 by 0.05 but don't touch M1", 'Tilt M2 by'],
    // opt-in failures round: the walk and tilt plan lines say "Move mirror M2…", so leaving the mirrors alone conflicts
    ['maximise the power without moving M2', 'clarify', 'conflict'],
    ['maximise power but leave the mirrors alone', 'clarify', 'conflict'],
    ['maximise power without touching any mirror', 'clarify', 'conflict'],
    ["walk M2 but don't touch the mirrors", 'clarify', 'conflict'],
    ["tilt M2 but don't move any mirrors", 'clarify', 'conflict'],
    ['move stage X to 12,4 mm', 'Move stage X'],
    ['M2 is off by 0.12 degrees', 'clarify', 'statement'],
    ['move stage X to 12.4 mm and raise the limit', 'clarify', 'partial'],
    ['move stage X to 12.4 mm but do not raise the limit', 'Move stage X'],
    ["move stage X to 12.4 mm but don't go past the limit", 'Move stage X'],
    ["move stage X to 12.4 mm but don't stop at the limit", 'clarify', 'conflict'],
    ['increase the laser power', 'clarify', 'partial'],
    ['open the shutter but do not increase the power', 'Open the shutter'],
    ['walk M2 without a stop rule', 'clarify', 'conflict'],
    ['walk M2 with no stop rule', 'clarify', 'conflict'],
    ['walk M2 but no stop rule', 'clarify', 'conflict'],
    ['walk M2 and stop when a step gains less than 1%', 'Walk M2 to'],
    ['open the shutter and report every minute', 'clarify', 'values'],
    ["if the power doesn't stop dropping, tell me", 'clarify', 'halt'],
    ['tell me if the shutter is not open', 'clarify', 'conflict'],
    // "hands off M2" is a refusal of M2, not a stop
    ['hands off M2 and maximise power', 'clarify', 'conflict'],
    ['keep your hands off M2 and maximise the power', 'clarify', 'conflict'],
    [LONG, 'clarify'],
  ],
  elder: [
    // already in the tests
    ['tell me when mum wakes up', 'Let me know when mum'],
    ['no cameras in her room please', 'Let me know when mum'],
    ['is she up yet', 'Let me know when mum'],
    ["I don't want a camera in her bedroom, just let me know when she's up", 'Let me know when mum'],
    ['help her not fall at night', 'If she gets up at night'],
    ['never let mum fall', 'If she gets up at night'],
    ['dont let the kettle boil dry', 'Tell me if the kettle'],
    ['tell me if she leaves the kettle on', 'Tell me if the kettle'],
    ['what if she leaves something on', 'Tell me if the kettle'],
    ['is the kettle safe', 'Tell me if the kettle'],
    ['so how does this work', 'clarify'],
    // from the wf4 review suggestions
    ['tell me if mum falls', 'clarify'],
    ['alert me if she falls over', 'clarify'],
    ['let me know if she falls', 'clarify'],
    ['let me know if the fridge door is left open', 'clarify'],
    ['let me know if she goes out the front door', 'clarify'],
    ['tell me if the heating is off', 'clarify'],
    ['tell me if she falls asleep with the TV on', 'clarify'],
    ['put a camera in her bedroom', 'clarify'],
    ['tell me if she trips', 'clarify'],
    ['what if she leaves the stove on', 'Tell me if the kettle'],
    ['let me know when mum is up', 'Let me know when mum'],
    ['tell me if she leaves the flat', 'clarify'],
    ['tell me if something is wrong', 'clarify'],
    ['what if she falls in the night?', 'clarify'],
    ['alert me if she leaves the house at night', 'clarify'],
    ['has she been out today', 'clarify'],
    ['has mum been up yet', 'Let me know when mum'],
    ['put a camera in her room', 'clarify'],
    ['call an ambulance if she falls', 'clarify'],
    ['tell me if the kettle is on for 30 minutes', 'clarify'],
    ['turn off the night light', 'clarify'],
    ["don't tell me when she's up", 'refuse', 'none'],
    ['light the way but leave the hall light off', 'clarify'],
    // wf5: more phrasings, typos, casing, emoji, rambling, questions, negations, opposites, other numbers, units and devices, several requests at once, edge input
    ["let me know when mum's up and tell me if the kettle's left on", 'clarify'],
    ['if she gets up at night light the way and tell me when she is up in the morning', 'clarify'],
    ['let me know when mum gets up', 'Let me know when mum'],
    ['text me when she wakes up', 'Let me know when mum'],
    ['I want to know when my mother gets out of bed', 'Let me know when mum'],
    ["Tell me when Mum's up", 'Let me know when mum'],
    ['no camera please, just tell me when she is up', 'Let me know when mum'],
    ['watch her with a camera', 'clarify'],
    ['light the way to the bathroom at night', 'If she gets up at night'],
    ['if she gets up at night turn on the hall light', 'If she gets up at night'],
    ['night light at 50%', 'clarify'],
    ['make the hall light brighter', 'clarify'],
    ['light the way to the kitchen', 'clarify'],
    ['tell me if the kettle is left on', 'Tell me if the kettle'],
    ['turn the kettle off after 10 minutes', 'Tell me if the kettle'],
    ['switch off the kettle', 'clarify'],
    ['switch on the kettle', 'clarify'],
    ['is the kettle on?', 'clarify'],
    ['remind her to take her pills', 'clarify'],
    ['call me if she falls', 'clarify'],
    ['detect falls', 'clarify'],
    ["don't wake her up", 'refuse'],
    ['keep the lights dim at night', 'If she gets up at night'],
    ['what time does she usually get up?', 'clarify'],
    ["tell me if she hasn't got up by 10", 'clarify'],
    ['tell me if the kettle is on for more than 10 mins', 'Tell me if the kettle'],
    ["tell me if the kettle's been on for 10 seconds", 'clarify'],
    ['let mum fall', 'refuse', 'opposite'],
    ['KETTLE ALERT ☕', 'Tell me if the kettle'],
    ['mum', 'clarify'],
    ['is mum ok?', 'clarify'],
    ['', 'clarify'],
    ['!!!', 'clarify'],
    ['10', 'clarify'],
    ['avísame cuando mamá se levante', 'clarify'],
    ['http://mum-cam.example/live', 'clarify'],
    // wf6 engine round: a switch-on with no condition is not a rule; a person's state in a condition; avoid phrases
    // in order; hypothetical with-states; negated and conditional switch-offs
    ['turn on the night light', 'clarify', 'partial'],
    ['turn the hall light on', 'clarify', 'partial'],
    ['put the night light on at 20%', 'clarify', 'partial'],
    ['hall light at 30%', 'clarify', 'partial'],
    ['switch on the hall light when she gets up', 'If she gets'],
    ["let me know if she hasn't got up by 9:30", 'Let me know'],
    ["let me know if she isn't up by 9:30", 'Let me know'],
    ["let me know if she's not up", 'Let me know'],
    ["message me if she's not up yet", 'Let me know'],
    ['tell me if she is not up in the morning', 'Let me know'],
    ['let me know if mum is not up by nine', 'Let me know'],
    ['turn the hall light off at night', 'clarify', 'halt'],
    ['turn the lights off at night', 'clarify', 'halt'],
    ['switch the lights off at night', 'clarify', 'halt'],
    ['let me know if the kettle is on the boil for 10 minutes', 'Tell me if'],
    ['the kettle might boil dry', 'Tell me if'],
    ["tell me if the kettle is still on when she's asleep", 'Tell me if'],
    ['boil the kettle', 'clarify', 'none'],
    ['what if she goes out with the kettle on', 'Tell me if'],
    ['what if she leaves the house with the kettle on', 'Tell me if'],
    ['tell me if she goes out with the kettle on', 'Tell me if'],
    ["tell me if the kettle's been on for more than 10 minutes, don't switch it off", 'clarify', 'conflict'],
    ['what if she nods off with the kettle on', 'Tell me if'],
    ["tell me if the kettle's auto-off is broken", 'Tell me if'],
    ["what if the kettle's auto-off doesn't work", 'Tell me if'],
    ["tell me if the kettle doesn't turn off", 'Tell me if'],
    ["what if the kettle doesn't switch itself off", 'Tell me if'],
    ['turn the kettle plug off after 10 minutes', 'Tell me if'],
    ['turn on the kettle', 'clarify', 'partial'],
    ["let me know when she's up but don't message pat", 'Let me know'],
    ['tell me if the kettle is on for more than 10 minutes and switch it off', 'Tell me if'],
    ['if the kettle is on for more than 10 minutes, turn the kettle plug off', 'Tell me if'],
    ["tell me if the kettle's been on too long but leave the switch alone", 'clarify', 'partial'],
    ['when she gets up, turn the hall light off', 'clarify', 'partial'],
    ["when she's up, turn the night light off", 'clarify', 'partial'],
    ["I don't want her to fall", 'If she gets'],
    ["don't light the way", 'refuse', 'none'],
    // getting into bed is not getting up; still in bed in the morning is
    ["let me know when she's in bed", 'clarify', 'partial'],
    ['let me know if she gets in bed', 'clarify', 'partial'],
    ["tell me if she's still in bed", 'Let me know when mum'],
    ["let me know when she's up and keep recordings", 'clarify', 'partial'], // "recordings" is still "record"
    // the kettle stopping after 10 minutes is the kettle request; a device that stops working is no request, and the
    // flat's other devices are not the kettle request's "10 minutes"
    ['make sure the kettle stops after 10 minutes', 'Tell me if the kettle'],
    ["tell me if the kettle hasn't stopped after 10 minutes", 'Tell me if the kettle'],
    ["make sure the kettle stops after 10 minutes while I'm at work", 'Tell me if the kettle'],
    ["tell me if the kettle's auto-off breaks", 'Tell me if the kettle'],
    ["tell me if she fails to get up by 9:30", 'Let me know when mum'],
    ['tell me if the kettle plug stops working', 'clarify'],
    ['let me know if the kettle plug goes offline', 'clarify'],
    ['let me know if the kettle plug breaks', 'clarify'],
    ['tell me if the kettle plug breaks in the morning', 'clarify'],
    ['let me know if the kettle stopped working', 'clarify'],
    ['let me know if the bed sensor breaks', 'clarify'],
    ['let me know if the bed sensor fails', 'clarify'],
    ['tell me when the kettle stops boiling', 'clarify'],
    ['tell me if the hall light is on for more than 10 minutes', 'clarify'],
    ['switch the hall light off after 10 minutes', 'clarify'],
    ['tell me if the door is open for more than 10 minutes', 'clarify'],
    // final round: a device that dies or disconnects is a phrase (DEVICE_DEAD), so a bereavement or a flaky wifi said
    // alongside a request doesn't ask back
    ["since dad died she lives alone, let me know when she's up in the morning", "Let me know when mum's up"],
    ["let me know when she's up, my dad died last year", "Let me know when mum's up"],
    ['her wifi disconnects sometimes, let me know when mum gets up', "Let me know when mum's up"],
    ["tell me if the kettle's been on for 10 minutes, since dad died she forgets things", "Tell me if the kettle's been on"],
    ["let me know if she leaves the kettle on, the auto-off is dead", "Tell me if the kettle's been on"],
    [LONG, 'clarify'],
  ],
  warehouse: [
    // already in the tests
    ['ship todays orders to dock 2', 'Move today'],
    ['start everything', 'Move today'],
    ['send fragile stuff to lane b', 'Divert anything'],
    ['STOP!!!', 'Stop everything'],
    ['shut down the line', 'Stop everything'],
    ['kill the conveyor', 'Stop everything'],
    ['turn off the conveyors', 'Stop everything'],
    ['abort', 'Stop everything'],
    ["don't stop the line", 'refuse', 'none'],
    // from the wf4 review suggestions
    ['restart C2', 'clarify'],
    ['restart everything', 'Move today'],
    ['pause the conveyors', 'Stop everything'],
    ['emergency stop', 'Stop everything'],
    ['close the dock', 'clarify'],
    ['stop cart B', 'clarify'],
    ['move 100 parcels to dock 3', 'clarify'],
    ['send fragile to lane c', 'clarify'],
    ['move the 40 parcels to dock 2', 'Move today'],
    ['emergency stop!', 'Stop everything'],
    ["divert fragile to lane B, don't stop the line", 'Divert anything'],
    ['stop everything except the carts', 'clarify', 'conflict'],
    ['stop everything but not the scanner', 'clarify', 'conflict'],
    // wf5: more phrasings, typos, casing, emoji, rambling, questions, negations, opposites, other numbers, units and devices, several requests at once, edge input
    ['stop everything and divert fragile to lane B', 'clarify'],
    ['divert fragile parcels to lane B', 'Divert anything'],
    ["don't stop everything, safely, now", 'refuse'],
    ['ok resume now', 'clarify'],
    ['is it running now?', 'clarify'],
    ['move the parcels to dock 2', 'Move today'],
    ['move 40 parcels to dock 2', 'Move today'],
    ['move 50 parcels to dock 2', 'clarify'],
    ["send today's orders to dock 1", 'clarify'],
    ['ship everything to dock 2', 'Move today'],
    ['move the parcels without scanning them', 'clarify'],
    ['move the parcels to dock 2 but skip the scanner', 'clarify'],
    ['divert fragile to lane A', 'clarify'],
    ['sort the fragile boxes into lane b', 'Divert anything'],
    ['divert anything heavy to lane B', 'clarify'],
    ['stop cart A', 'clarify'],
    ['stop C1', 'clarify'],
    ['stop the gate', 'clarify'],
    ['turn off the lights', 'clarify'],
    ['freeze!', 'Stop everything'],
    ['halt the line', 'Stop everything'],
    ['pause everything', 'Stop everything'],
    ['stop everything except the scanner', 'clarify'],
    ['stop everything but keep the scanner running', 'clarify'],
    ['stop the conveyors but not the carts', 'clarify'],
    ["stop everything but don't close the dock", 'clarify'],
    ['shut the dock', 'clarify'],
    ['close dock 2', 'clarify'],
    ["don't stop", 'refuse'],
    ['keep going', 'clarify'],
    ['E-STOP', 'Stop everything'],
    ['kill it', 'Stop everything'],
    ["what's on conveyor 2?", 'clarify'],
    ['', 'clarify'],
    ['---', 'clarify'],
    ['42', 'clarify'],
    ['停止所有设备', 'clarify'],
    ['https://wms.example.com/dock/2', 'clarify'],
    // wf6 engine round: "everything but X" leaves X out; kept motion; all of them is not the fragile-only rule; a dock's
    // number is its name; how a stop is triggered; starting what the plan keeps parked; a gate the plan sends to lane B
    ['is it possible to divert anything scanned as fragile to lane B?', 'Divert anything scanned'],
    ["make sure the line doesn't stop", 'clarify', 'partial'],
    ["tell me if the line doesn't stop", 'clarify', 'partial'],
    ["the carts didn't stop last time", 'clarify', 'partial'],
    ['if a cart jams, switch it off', 'clarify', 'partial'],
    ['when I leave, turn the lights off', 'clarify', 'partial'],
    ["once I've left, turn the heating off", 'clarify', 'partial'],
    ['let me know if dock 2 is not open', 'clarify', 'partial'],
    ['stop the conveyors now', 'Stop everything, safely'],
    ['move the parcels to the dock now', "Move today's 40"],
    ['stop everything but keep the carts moving', 'clarify', 'conflict'],
    ['stop everything but keep the scanner on', 'clarify', 'conflict'],
    ['stop everything but keep the belts on', 'clarify', 'conflict'],
    ['stop everything but the carts', 'clarify', 'conflict'],
    ['stop all but the carts', 'clarify', 'conflict'],
    ['stop everything but the scanner', 'clarify', 'conflict'],
    ['stop everything but the conveyors', 'clarify', 'conflict'],
    ['divert everything scanned as fragile to lane B', 'Divert anything scanned'],
    ['divert everything fragile to lane b', 'Divert anything scanned'],
    ['divert every fragile parcel to lane B', 'Divert anything scanned'],
    ['divert all fragile parcels to lane b', 'Divert anything scanned'],
    ['divert all of the fragile parcels to lane b', 'Divert anything scanned'],
    ['sort all the fragile boxes to lane b', 'Divert anything scanned'],
    ['divert heavy fragile parcels to lane b', 'clarify', 'partial'],
    ['divert all the parcels to lane b', 'clarify', 'partial'],
    ['divert all parcels to lane b', 'clarify', 'partial'],
    ['divert everything to lane B', 'clarify', 'partial'],
    ['divert every parcel to lane B', 'clarify', 'partial'],
    ['send every box to lane b', 'clarify', 'partial'],
    ['divert all but the fragile ones to lane b', 'clarify', 'partial'],
    ['stop all', 'Stop everything, safely'],
    ['stop dock 2', 'clarify', 'partial'],
    ['stop everything and close dock 2', 'clarify', 'partial'],
    ['close dock 2 and stop', 'clarify', 'partial'],
    ['stop the line at dock 2', 'clarify', 'partial'],
    ['stop conveyor 2', 'clarify', 'partial'],
    ['move 2 parcels to dock 2', 'clarify', 'values'],
    ['press the e-stop', 'Stop everything, safely'],
    ['hit the emergency stop', 'Stop everything, safely'],
    ['press stop', 'Stop everything, safely'],
    ['push the stop button', 'Stop everything, safely'],
    ['hit the e-stop button', 'Stop everything, safely'],
    ['estop', 'Stop everything, safely'],
    ['stop the whole line', 'Stop everything, safely'],
    ['stop the entire line', 'Stop everything, safely'],
    ['press the button', 'clarify', 'none'],
    ['hit the gate', 'clarify', 'none'],
    ['start the carts', 'clarify', 'partial'],
    ['move the carts', 'clarify', 'partial'],
    ['run the carts to dock 2', 'clarify', 'partial'],
    ['start the line', "Move today's 40"],
    ['start the scanner', "Move today's 40"],
    ['move the parcels, no carts', 'clarify', 'conflict'],
    ['stop everything except for the carts', 'clarify', 'conflict'],
    ['stop everything but for the carts', 'clarify', 'conflict'],
    ['stop all, but the carts', 'clarify', 'conflict'],
    ['stop everything, but the carts', 'clarify', 'conflict'],
    ['stop everything but keep the carts going', 'clarify', 'conflict'],
    ['stop everything but let the carts keep going', 'clarify', 'conflict'],
    ['stop everything but leave the carts moving', 'clarify', 'conflict'],
    ['stop everything but the carts keep moving', 'clarify', 'conflict'],
    ['stop everything, the carts can keep going', 'clarify', 'conflict'],
    ['stop the belts but keep the carts moving', 'clarify', 'conflict'],
    ['stop all the belts but the carts keep going', 'clarify', 'conflict'],
    ['everything but the carts should stop', 'clarify', 'conflict'],
    ['everything except the carts should stop', 'clarify', 'conflict'],
    ['turn everything off but the carts', 'clarify', 'conflict'],
    ['shut everything down but the carts', 'clarify', 'conflict'],
    ['keep the gate closed', 'clarify', 'none'],
    ['divert fragile to lane b but keep the gate closed', 'clarify', 'conflict'],
    ['divert fragile parcels to lane b and keep the gate closed', 'clarify', 'conflict'],
    // quantifiers: "every label" or "the whole shift" doesn't widen the rule; "the entire batch", "each parcel" does
    ['check every label, fragile goes to lane B', 'Divert anything'],
    ['divert fragile parcels to lane B for the whole shift', 'Divert anything'],
    ['divert every parcel scanned as fragile to lane B', 'Divert anything'],
    ['divert all glass to lane B', 'Divert anything'],
    ['divert the entire batch to lane B', 'clarify'],
    ['divert each parcel to lane B', 'clarify'],
    ['divert the lot to lane B', 'clarify'],
    ['divert some parcels to lane B', 'clarify'],
    // …and a quantifier rules out only itself: not "something", "sometimes", "mostly", "entirely", "leave the rest"
    ['divert fragile to lane B, something like glassware', 'Divert anything'],
    ['sometimes glass comes through, divert fragile to lane B', 'Divert anything'],
    ['divert fragile to lane B, mostly glass', 'Divert anything'],
    ['divert fragile to lane B entirely', 'Divert anything'],
    ['divert fragile to lane B and leave the rest', 'Divert anything'],
    [LONG, 'clarify'],
  ],
  creator: [
    // already in the tests
    ['go live pls', 'Go live.'],
    ['turn on the on-air sign', 'Go live.'],
    ['turn on the stream', 'Go live.'],
    ['turn the stream on', 'Go live.'],
    ['go live but keep the mic muted', 'clarify', 'conflict'],
    ['im done, end the stream', "I'm done. Wrap up."],
    ['mic off', "I'm done. Wrap up.", 'none'],
    ['turn off the camera', "I'm done. Wrap up.", 'none'],
    ['record a video without streaming', 'Recording only'],
    ["I don't want to stream tonight, just record", 'Recording only'],
    ["don't go live", 'refuse'],
    ["I really don't want to go live", 'refuse'],
    ["we're not going live today", 'refuse'],
    ['never mind', 'refuse'],
    // from the wf4 review suggestions
    ["Record, don't turn on the sign.", 'Recording only'],
    ["Record it, don't go live", 'Recording only'],
    ["Go live, don't turn on the sign", 'clarify'],
    ['turn on the key light', 'clarify'],
    ["Just record, don't stream.", 'Recording only'],
    ['go live without the sign', 'clarify', 'conflict'],
    ['key light off', 'clarify', 'partial'],
    ['lights off', 'clarify', 'partial'],
    ['strip off', 'clarify', 'partial'],
    ['go live but mute the mic', 'clarify'],
    ['turn off the key light', 'clarify'],
    ['end stream but keep recording', 'clarify'],
    ['go live on twitch at 9pm', 'clarify'],
    ["we won't go live today", 'refuse'],
    ['no need to go live', 'refuse'],
    ['no thanks', 'refuse'],
    ['stop recording', 'clarify', 'partial'],
    ['mute the mic', "I'm done. Wrap up."],
    ['no stream tonight, just record locally', 'Recording only'],
    ['https://studio.youtube.com/channel/UC123/livestreaming', 'clarify'],
    ["go live but don't turn on the sign", 'clarify'],
    ['go live except the sign', 'clarify'],
    ['wrap up but leave the camera on', 'clarify'],
    ["record only, don't turn on the key light", 'clarify'],
    ['no, go live', 'Go live.'],
    // wf5: more phrasings, typos, casing, emoji, rambling, questions, negations, opposites, other numbers, units and devices, several requests at once, edge input
    ["Go live. I'm done. Wrap up.", 'clarify'],
    ['go live and then wrap up', 'clarify'],
    ['record, then go live', 'clarify'],
    ['go live and turn off the camera', 'clarify'],
    ['ok go live without the sign now', 'clarify'],
    ['go live but mute the mic now', 'clarify'],
    ['stream, no recording', 'Go live.'],
    ['only stream', 'Go live.'],
    ['GO LIVE', 'Go live.'],
    ['go live now!!!', 'Go live.'],
    ['start the stream', 'Go live.'],
    ['start streaming', 'Go live.'],
    ["let's go live on YouTube", 'Go live.'],
    ['go live at 9pm', 'clarify'],
    ['go live with the backup camera', 'clarify'],
    ['go live, mic muted', 'clarify'],
    ['go live with the mic muted', 'clarify'],
    ['go live without the on-air sign', 'clarify'],
    ['go live, no on-air sign', 'clarify'],
    ['record a video', 'Recording only'],
    ['start recording', 'Recording only'],
    ['record without the mic', 'clarify'],
    ['record but leave the sign off', 'Recording only'],
    ["i'm done", "I'm done. Wrap up."],
    ["that's it for today, wrap it up", "I'm done. Wrap up."],
    ['end the stream', "I'm done. Wrap up."],
    ['stop streaming', "I'm done. Wrap up."],
    ['wrap up but leave the key light on', "I'm done. Wrap up."],
    ['wrap up but leave the mic on', 'clarify'],
    ['wrap up and turn everything off', 'clarify'],
    ['turn everything off', 'clarify'],
    ['turn off the lights', 'clarify'],
    ['kill the lights', 'clarify'],
    ['sign off', "I'm done. Wrap up."],
    ['go live and record at the same time', 'clarify'],
    ["go live, don't record", 'Go live.'],
    ['never go live', 'refuse'],
    ['go live? no.', 'refuse'],
    ['record the stream', 'clarify'],
    ['I want to record but not stream', 'Recording only'],
    ["I don't want to record, I want to stream", 'Go live.'],
    ['go live with the key light at 60%', 'clarify'],
    ['make the strip purple', 'clarify'],
    ['go live 🎥🔴', 'Go live.'],
    ['', 'clarify'],
    ['    \n\t  ', 'clarify'],
    ['!!!???', 'clarify'],
    ['1080', 'clarify'],
    ['开始直播', 'clarify'],
    ['https://twitch.tv/somecreator', 'clarify'],
    // wf6 engine round: kick off, light it up and turn it up; the plan's own set points; with no mic; kill everything;
    // and this round's creator routing
    ["if the stream doesn't stop, tell me", 'clarify', 'halt'],
    ['when she gets up, turn the hall light off', 'clarify', 'partial'],
    ['let me know if the stream is not live', 'clarify', 'partial'],
    ['kick off the stream', 'Go live'],
    ['go live with the key light at 80%', 'Go live'],
    ['go live at 1%', 'clarify', 'values'],
    ['wrap up and leave the key light at 30%', "I'm done. Wrap"],
    ['am i live?', 'clarify', 'question'],
    ['record with no mic', 'clarify', 'conflict'],
    ['record with no camera', 'clarify', 'conflict'],
    ['kill everything', 'clarify', 'partial'],
    ['wrap up, skip the thanks for watching', 'clarify', 'conflict'],
    ['light it up', 'clarify', 'none'],
    ['lights up', 'clarify', 'none'],
    ['turn it up', 'clarify', 'none'],
    ['put the sign up', 'Go live'],
    ['set the stream up', 'Go live'],
    ['fire the stream up', 'Go live'],
    ['wrapping up', "I'm done. Wrap"],
    ['turn everything on', 'clarify', 'none'],
    ['switch everything on', 'clarify', 'none'],
    ['everything on', 'clarify', 'none'],
    ['set up for streaming', 'Go live'],
    ['fire up the stream', 'Go live'],
    ['pause the stream', 'clarify', 'halt'],
    ['cut the stream', "I'm done. Wrap"],
    ['go dark', 'clarify', 'none'],
    ['ending the stream now', "I'm done. Wrap"],
    ['stream ended', "I'm done. Wrap"],
    ['stopped streaming', "I'm done. Wrap"],
    ['go live without the webcam', 'clarify', 'conflict'],
    ['go live, no backup', 'clarify', 'conflict'],
    ['go live but keep the lights off', 'clarify', 'conflict'],
    ['go live with the strip blue', 'clarify', 'partial'],
    ['record from the webcam', 'clarify', 'partial'],
    ['switch to the backup camera', 'clarify', 'partial'],
    ['record my screen', 'clarify', 'partial'],
    ['record video only', 'clarify', 'none'],
    ['silent recording', 'clarify', 'none'],
    ['check everything', 'clarify', 'none'],
    ["the camera isn't working", 'clarify', 'none'],
    ['put up starting soon', 'clarify', 'none'],
    ['record without the webcam', 'Recording only —'],
    ['begin recording', 'Recording only —'],
    ['record with the mic off', 'clarify', 'partial'],
    ['record with the sound off', 'clarify', 'partial'],
    ['wrap up with the lights off', 'clarify', 'partial'],
    ["I'm done, but keep the stream going", 'clarify', 'conflict'],
    ['wrap up without the thanks screen', 'clarify', 'conflict'],
    ['wrap up, no thanks screen', 'clarify', 'conflict'],
    ['wrap up but skip the thank you screen', 'clarify', 'conflict'],
    ['wrap up without thanks for watching', 'clarify', 'conflict'],
    [LONG, 'clarify'],
  ],
};

// When a clarify names chips, these must be among them ("keep the camera on while I'm away" must not offer only chips
// that have nothing to do with the camera). A plain clarify that names none is fine.
const NAMED = {
  home: [["keep the camera on while I'm away", 'Hold the house']],
  creator: [["Go live. I'm done. Wrap up.", 'Go live.'], ['go live and then wrap up', 'Go live.']],
  elder: [["let me know when mum's up and tell me if the kettle's left on", 'Tell me if the kettle']],
};

// A typed "what if <device> fails?" (or "tell me if <device> stops working") while the chips are up: the page says how
// to pick a failure (true), rather than route it as a request. A person, or something that isn't a device of the
// scene, is not one (false), nor is a device doing its job ("…goes dark") or a failure to do something ("…fails to…").
export const WHATIF_QUESTIONS = {
  home: [['tell me if the pump stops working', true], ['let me know if the plants die', false], ['what if the pump dies?', true], ['what if the blinds break', true], ['what if it goes offline', true], ['what if the power goes out', false], ['what if it rains', false], ['what if the wifi goes down', false]],
  lab: [['what if M2 fails', true], ['what if the laser stops working', true], ['what if the power drops', false], ['let me know if the laser fails', true], ['tell me if the meter stops responding', true]],
  elder: [['what if the hall light stops working?', true], ['what if something fails?', true], ['What happens if the bed sensor dies?', true], ['what if the kettle breaks', true], ["what if the kettle's auto-off fails", true],
    ['what if she leaves something on', false], ['what if mum dies', false], ['what if she falls', false], ['what if mum dies in bed', false], ["Tell me if the kettle's been on for more than 10 minutes.", false],
    ['tell me if the kettle plug stops working', true], ["let me know if the bed sensor isn't working", true], ['tell me if the kettle plug goes dead', true],
    ['tell me if the kettle plug has stopped working', true], ['let me know when the bed sensor loses power', true], ['what if the kettle plug loses power', true],
    ["tell me if the kettle's auto-off fails", false], ['let me know if she dies', false], ['tell me if the hall light goes dark', false], ['let me know if she fails to get up', false]],
  warehouse: [['tell me if the scanner fails to read a label', false], ['let me know if cart B goes offline', true], ['what if cart B goes offline', true], ['what if a conveyor breaks down', true], ['what if C2 fails', true], ['what if a parcel falls off', false]],
  creator: [['what if my camera dies mid-stream', true], ['what if the mic cuts out', true], ['what if nobody watches', false], ['Go live.', false]],
};

const VIAS = { run: [undefined, 'clause'], refuse: [undefined, 'opposite'], clarify: [undefined, 'halt', 'tie', 'values', 'partial', 'conflict', 'question', 'check', 'statement'] };
function shapeProblem(r, prompts) {
  if (!r || !VIAS[r.action]) return `action ${r && r.action}`;
  if (!VIAS[r.action].includes(r.via)) return `${r.action} with via "${r.via}"`;
  if (!prompts.includes(r.prompt)) return 'prompt is not one of the scene prompts';
  if (typeof r.score !== 'number' || Number.isNaN(r.score)) return 'score is not a number';
  if (r.via === 'tie' && (!prompts.includes(r.also) || r.also === r.prompt)) return 'tie without a second chip';
  if (r.via === 'conflict' && typeof r.line !== 'string') return 'conflict without its plan line';
  return null;
}
const strict = (text, prompts) => interpret(text, prompts, { strict: true }); // rethrows instead of answering "clarify"

export function routingChecks({ report, scenes }) {
  for (const [id, cases] of Object.entries(CASES)) {
    const scene = scenes[id]; if (!scene) continue;
    const P = scene.prompts, problems = [];
    for (const [text, want, via] of cases) {
      let r; try { r = strict(text, P); } catch (e) { problems.push(`"${text.slice(0, 60)}" threw: ${e.message}`); continue; }
      const shape = shapeProblem(r, P); if (shape) { problems.push(`"${text.slice(0, 60)}": ${shape}`); continue; }
      const got = r.action === 'run' ? r.prompt.chip : r.action;
      const ok = (want === 'refuse' || want === 'clarify' ? r.action === want : r.action === 'run' && r.prompt.chip.startsWith(want)) && (!via || (via === 'none' ? !r.via : r.via === via));
      if (!ok) problems.push(`"${text.slice(0, 60)}" → ${r.action === 'run' ? `runs "${got.slice(0, 40)}"` : got}${r.via ? ` (${r.via})` : ''} (score ${r.score}), expected ${want === 'refuse' || want === 'clarify' ? want : `"${want}…"`}${via ? ` (${via})` : ''}`);
    }
    for (const [text, chip] of NAMED[id] || []) {
      const r = strict(text, P); const named = r.action === 'clarify' && r.via ? [r.prompt, r.also].filter(Boolean) : null;
      if (r.action !== 'clarify' || (named && !named.some((p) => p.chip.startsWith(chip)))) problems.push(`"${text}" → ${r.action}/${r.via}, naming ${(named || []).map((p) => `"${p.chip.slice(0, 24)}"`).join(' and ')}: expected "${chip}…" among them`);
    }
    // every chip must still run itself
    for (const p of P) { const r = strict(p.chip, P); if (r.action !== 'run' || r.prompt !== p) problems.push(`chip "${p.chip.slice(0, 40)}" → ${r.action} ${r.action === 'run' ? `"${r.prompt.chip.slice(0, 30)}"` : ''}`); }
    report(`${id} · typed requests route correctly (${cases.length} phrasings)`, problems);
    const wq = (WHATIF_QUESTIONS[id] || []).filter(([text, want]) => asksWhatIfFails(text, scene.devices) !== want).map(([text, want]) => `"${text}" ${want ? 'is' : 'is not'} a what-if about a device failing`);
    report(`${id} · a typed "what if … fails?" gets how to pick a failure, and nothing else does`, wq);

    // never throws, always a well-formed answer: odd input and a seeded word salad from this scene's own words
    const fuzz = [];
    for (const v of [null, undefined, 42, {}, [], '\u0000', '\n\t', 'x'.repeat(100000)]) { try { const s = shapeProblem(strict(v, P), P); if (s) fuzz.push(`${typeof v}: ${s}`); } catch (e) { fuzz.push(`${typeof v} threw: ${e.message}`); } }
    const vocab = [...new Set(P.flatMap((p) => [...p.chip.split(/\s+/), ...(p.keywords || [])]))].concat(["don't", 'not', 'no', 'but', 'except', 'without', 'keep', 'leave', 'turn', 'off', 'on', 'open', 'close', 'stop', 'what', 'is', 'if', 'let', 'just', 'only', ',', '.', '?', '12.4', '5', '°F', 'mm', 'cm', '%', 'M1', 'lane C', 'cart B', 'dock 3', '🙂']);
    let seed = 11; const rnd = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);
    for (let k = 0; k < 400 && fuzz.length < 5; k++) {
      const text = Array.from({ length: 1 + Math.floor(rnd() * 12) }, () => vocab[Math.floor(rnd() * vocab.length)]).join(' ');
      try { const s = shapeProblem(strict(text, P), P); if (s) fuzz.push(`"${text}": ${s}`); } catch (e) { fuzz.push(`"${text}" threw: ${e.message}`); }
    }
    report(`${id} · typed requests never throw and always get a well-formed answer`, fuzz);

    // 2000 characters stay fast: median of 15 calls under 10 ms (well under a frame), for text shaped to make the engine
    // work hardest. The best of up to five rounds counts, so a busy machine (other processes, browsers, garbage
    // collection) doesn't fail the check, while an engine that is really slower still does. Unloaded, each shape takes
    // 0.2 to 2.5 ms.
    const fill = (s) => s.repeat(Math.ceil(2000 / s.length)).slice(0, 2000);
    const shapes = { story: LONG, chips: fill(P.map((p) => p.chip).join(' ') + ' '), negations: fill(`don't ${P[0].chip}, ${P.slice(1).map((p) => p.chip).join(', ')}, `), vague: fill("don't do that, hmm, something else, maybe later, "), contrasts: fill(`${P[0].chip} but ${P[P.length - 1].chip} but `), states: fill('keep the mic muted, leave the sign off, with the shutter closed, turn the lights off, ') };
    const slow = [];
    for (const [name, text] of Object.entries(shapes)) {
      let best = Infinity;
      for (let round = 0; round < 5 && best > 10; round++) { const ms = []; for (let i = 0; i < 15; i++) { const t0 = performance.now(); strict(text, P); ms.push(performance.now() - t0); } ms.sort((a, b) => a - b); best = Math.min(best, ms[7]); }
      if (best > 10) slow.push(`${name}: ${best.toFixed(2)} ms`);
    }
    report(`${id} · 2000-character requests are answered in under 10 ms`, slow);
  }
}
